config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :nationalities
  resources :mother_tongues
  resources :occupations
  resources :genders
  resources :obsessions
  resources :order_alignments
  resources :secret_languages
  resources :moral_alignments
  resources :eye_colours
  resources :skin_base_tones
  resources :favourite_foods
  resources :favourite_drinks
  resources :ailments
  resources :star_signs
  resources :lastnames
  resources :firstnames
  resources :characters
  root 'characters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
end

app/models/ailment.rb
class Ailment < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
end

app/models/eye_colour.rb
class EyeColour < ApplicationRecord
end

app/models/favourite_drink.rb
class FavouriteDrink < ApplicationRecord
end

app/models/favourite_food.rb
class FavouriteFood < ApplicationRecord
end

app/models/firstname.rb
class Firstname < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/lastname.rb
class Lastname < ApplicationRecord
end

app/models/moral_alignment.rb
class MoralAlignment < ApplicationRecord
end

app/models/mother_tongue.rb
class MotherTongue < ApplicationRecord
end

app/models/nationality.rb
class Nationality < ApplicationRecord
end

app/models/obsession.rb
class Obsession < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
end

app/models/order_alignment.rb
class OrderAlignment < ApplicationRecord
end

app/models/secret_language.rb
class SecretLanguage < ApplicationRecord
end

app/models/skin_base_tone.rb
class SkinBaseTone < ApplicationRecord
end

app/models/star_sign.rb
class StarSign < ApplicationRecord
end

app/controllers/lastnames_controller.rb
class LastnamesController < ApplicationController
  before_action :set_lastname, only: [:show, :edit, :update, :destroy]

  # GET /lastnames
  # GET /lastnames.json
  def index
    @lastnames = Lastname.all
  end

  # GET /lastnames/1
  # GET /lastnames/1.json
  def show
  end

  # GET /lastnames/new
  def new
    @lastname = Lastname.new
  end

  # GET /lastnames/1/edit
  def edit
  end

  # POST /lastnames
  # POST /lastnames.json
  def create
    @lastname = Lastname.new(lastname_params)

    respond_to do |format|
      if @lastname.save
        format.html { redirect_to @lastname, notice: 'Lastname was successfully created.' }
        format.json { render :show, status: :created, location: @lastname }
      else
        format.html { render :new }
        format.json { render json: @lastname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lastnames/1
  # PATCH/PUT /lastnames/1.json
  def update
    respond_to do |format|
      if @lastname.update(lastname_params)
        format.html { redirect_to @lastname, notice: 'Lastname was successfully updated.' }
        format.json { render :show, status: :ok, location: @lastname }
      else
        format.html { render :edit }
        format.json { render json: @lastname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lastnames/1
  # DELETE /lastnames/1.json
  def destroy
    @lastname.destroy
    respond_to do |format|
      format.html { redirect_to lastnames_url, notice: 'Lastname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lastname
      @lastname = Lastname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lastname_params
      params.require(:lastname).permit(:content)
    end
end

app/helpers/ailments_helper.rb
module AilmentsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/lastnames_helper.rb
module LastnamesHelper
end

app/views/lastnames/_form.html.erb
<%= form_with(model: lastname, local: true) do |form| %>
  <% if lastname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lastname.errors.count, "error") %> prohibited this lastname from being saved:</h2>

      <ul>
      <% lastname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :lastname_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lastnames/edit.html.erb
<h1>Editing Lastname</h1>

<%= render 'form', lastname: @lastname %>

<%= link_to 'Show', @lastname %> |
<%= link_to 'Back', lastnames_path %>

app/views/lastnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lastnames</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lastnames.each do |lastname| %>
      <tr>
        <td><%= lastname.content %></td>
        <td><%= link_to 'Show', lastname %></td>
        <td><%= link_to 'Edit', edit_lastname_path(lastname) %></td>
        <td><%= link_to 'Destroy', lastname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lastname', new_lastname_path %>

app/views/lastnames/new.html.erb
<h1>New Lastname</h1>

<%= render 'form', lastname: @lastname %>

<%= link_to 'Back', lastnames_path %>

app/views/lastnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @lastname.content %>
</p>

<%= link_to 'Edit', edit_lastname_path(@lastname) %> |
<%= link_to 'Back', lastnames_path %>