config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :nationalities
  resources :mother_tongues
  resources :occupations
  resources :genders
  resources :obsessions
  resources :order_alignments
  resources :secret_languages
  resources :moral_alignments
  resources :eye_colours
  resources :skin_base_tones
  resources :favourite_foods
  resources :favourite_drinks
  resources :ailments
  resources :star_signs
  resources :lastnames
  resources :firstnames
  resources :characters
  root 'characters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
end

app/models/ailment.rb
class Ailment < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
end

app/models/eye_colour.rb
class EyeColour < ApplicationRecord
end

app/models/favourite_drink.rb
class FavouriteDrink < ApplicationRecord
end

app/models/favourite_food.rb
class FavouriteFood < ApplicationRecord
end

app/models/firstname.rb
class Firstname < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/lastname.rb
class Lastname < ApplicationRecord
end

app/models/moral_alignment.rb
class MoralAlignment < ApplicationRecord
end

app/models/mother_tongue.rb
class MotherTongue < ApplicationRecord
end

app/models/nationality.rb
class Nationality < ApplicationRecord
end

app/models/obsession.rb
class Obsession < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
end

app/models/order_alignment.rb
class OrderAlignment < ApplicationRecord
end

app/models/secret_language.rb
class SecretLanguage < ApplicationRecord
end

app/models/skin_base_tone.rb
class SkinBaseTone < ApplicationRecord
end

app/models/star_sign.rb
class StarSign < ApplicationRecord
end

app/controllers/favourite_drinks_controller.rb
class FavouriteDrinksController < ApplicationController
  before_action :set_favourite_drink, only: [:show, :edit, :update, :destroy]

  # GET /favourite_drinks
  # GET /favourite_drinks.json
  def index
    @favourite_drinks = FavouriteDrink.all
  end

  # GET /favourite_drinks/1
  # GET /favourite_drinks/1.json
  def show
  end

  # GET /favourite_drinks/new
  def new
    @favourite_drink = FavouriteDrink.new
  end

  # GET /favourite_drinks/1/edit
  def edit
  end

  # POST /favourite_drinks
  # POST /favourite_drinks.json
  def create
    @favourite_drink = FavouriteDrink.new(favourite_drink_params)

    respond_to do |format|
      if @favourite_drink.save
        format.html { redirect_to @favourite_drink, notice: 'Favourite drink was successfully created.' }
        format.json { render :show, status: :created, location: @favourite_drink }
      else
        format.html { render :new }
        format.json { render json: @favourite_drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourite_drinks/1
  # PATCH/PUT /favourite_drinks/1.json
  def update
    respond_to do |format|
      if @favourite_drink.update(favourite_drink_params)
        format.html { redirect_to @favourite_drink, notice: 'Favourite drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourite_drink }
      else
        format.html { render :edit }
        format.json { render json: @favourite_drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourite_drinks/1
  # DELETE /favourite_drinks/1.json
  def destroy
    @favourite_drink.destroy
    respond_to do |format|
      format.html { redirect_to favourite_drinks_url, notice: 'Favourite drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite_drink
      @favourite_drink = FavouriteDrink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_drink_params
      params.require(:favourite_drink).permit(:content)
    end
end

app/helpers/ailments_helper.rb
module AilmentsHelper
end

app/helpers/favourite_drinks_helper.rb
module FavouriteDrinksHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/views/favourite_drinks/_form.html.erb
<%= form_with(model: favourite_drink, local: true) do |form| %>
  <% if favourite_drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite_drink.errors.count, "error") %> prohibited this favourite_drink from being saved:</h2>

      <ul>
      <% favourite_drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :favourite_drink_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourite_drinks/edit.html.erb
<h1>Editing Favourite Drink</h1>

<%= render 'form', favourite_drink: @favourite_drink %>

<%= link_to 'Show', @favourite_drink %> |
<%= link_to 'Back', favourite_drinks_path %>

app/views/favourite_drinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourite Drinks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourite_drinks.each do |favourite_drink| %>
      <tr>
        <td><%= favourite_drink.content %></td>
        <td><%= link_to 'Show', favourite_drink %></td>
        <td><%= link_to 'Edit', edit_favourite_drink_path(favourite_drink) %></td>
        <td><%= link_to 'Destroy', favourite_drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite Drink', new_favourite_drink_path %>

app/views/favourite_drinks/new.html.erb
<h1>New Favourite Drink</h1>

<%= render 'form', favourite_drink: @favourite_drink %>

<%= link_to 'Back', favourite_drinks_path %>

app/views/favourite_drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @favourite_drink.content %>
</p>

<%= link_to 'Edit', edit_favourite_drink_path(@favourite_drink) %> |
<%= link_to 'Back', favourite_drinks_path %>