config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :nationalities
  resources :mother_tongues
  resources :occupations
  resources :genders
  resources :obsessions
  resources :order_alignments
  resources :secret_languages
  resources :moral_alignments
  resources :eye_colours
  resources :skin_base_tones
  resources :favourite_foods
  resources :favourite_drinks
  resources :ailments
  resources :star_signs
  resources :lastnames
  resources :firstnames
  resources :characters
  root 'characters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
end

app/models/ailment.rb
class Ailment < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
end

app/models/eye_colour.rb
class EyeColour < ApplicationRecord
end

app/models/favourite_drink.rb
class FavouriteDrink < ApplicationRecord
end

app/models/favourite_food.rb
class FavouriteFood < ApplicationRecord
end

app/models/firstname.rb
class Firstname < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/lastname.rb
class Lastname < ApplicationRecord
end

app/models/moral_alignment.rb
class MoralAlignment < ApplicationRecord
end

app/models/mother_tongue.rb
class MotherTongue < ApplicationRecord
end

app/models/nationality.rb
class Nationality < ApplicationRecord
end

app/models/obsession.rb
class Obsession < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
end

app/models/order_alignment.rb
class OrderAlignment < ApplicationRecord
end

app/models/secret_language.rb
class SecretLanguage < ApplicationRecord
end

app/models/skin_base_tone.rb
class SkinBaseTone < ApplicationRecord
end

app/models/star_sign.rb
class StarSign < ApplicationRecord
end

app/controllers/order_alignments_controller.rb
class OrderAlignmentsController < ApplicationController
  before_action :set_order_alignment, only: [:show, :edit, :update, :destroy]

  # GET /order_alignments
  # GET /order_alignments.json
  def index
    @order_alignments = OrderAlignment.all
  end

  # GET /order_alignments/1
  # GET /order_alignments/1.json
  def show
  end

  # GET /order_alignments/new
  def new
    @order_alignment = OrderAlignment.new
  end

  # GET /order_alignments/1/edit
  def edit
  end

  # POST /order_alignments
  # POST /order_alignments.json
  def create
    @order_alignment = OrderAlignment.new(order_alignment_params)

    respond_to do |format|
      if @order_alignment.save
        format.html { redirect_to @order_alignment, notice: 'Order alignment was successfully created.' }
        format.json { render :show, status: :created, location: @order_alignment }
      else
        format.html { render :new }
        format.json { render json: @order_alignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_alignments/1
  # PATCH/PUT /order_alignments/1.json
  def update
    respond_to do |format|
      if @order_alignment.update(order_alignment_params)
        format.html { redirect_to @order_alignment, notice: 'Order alignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_alignment }
      else
        format.html { render :edit }
        format.json { render json: @order_alignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_alignments/1
  # DELETE /order_alignments/1.json
  def destroy
    @order_alignment.destroy
    respond_to do |format|
      format.html { redirect_to order_alignments_url, notice: 'Order alignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_alignment
      @order_alignment = OrderAlignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_alignment_params
      params.require(:order_alignment).permit(:content)
    end
end

app/helpers/ailments_helper.rb
module AilmentsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/order_alignments_helper.rb
module OrderAlignmentsHelper
end

app/views/order_alignments/_form.html.erb
<%= form_with(model: order_alignment, local: true) do |form| %>
  <% if order_alignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_alignment.errors.count, "error") %> prohibited this order_alignment from being saved:</h2>

      <ul>
      <% order_alignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :order_alignment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_alignments/edit.html.erb
<h1>Editing Order Alignment</h1>

<%= render 'form', order_alignment: @order_alignment %>

<%= link_to 'Show', @order_alignment %> |
<%= link_to 'Back', order_alignments_path %>

app/views/order_alignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Alignments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_alignments.each do |order_alignment| %>
      <tr>
        <td><%= order_alignment.content %></td>
        <td><%= link_to 'Show', order_alignment %></td>
        <td><%= link_to 'Edit', edit_order_alignment_path(order_alignment) %></td>
        <td><%= link_to 'Destroy', order_alignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Alignment', new_order_alignment_path %>

app/views/order_alignments/new.html.erb
<h1>New Order Alignment</h1>

<%= render 'form', order_alignment: @order_alignment %>

<%= link_to 'Back', order_alignments_path %>

app/views/order_alignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @order_alignment.content %>
</p>

<%= link_to 'Edit', edit_order_alignment_path(@order_alignment) %> |
<%= link_to 'Back', order_alignments_path %>