config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :nationalities
  resources :mother_tongues
  resources :occupations
  resources :genders
  resources :obsessions
  resources :order_alignments
  resources :secret_languages
  resources :moral_alignments
  resources :eye_colours
  resources :skin_base_tones
  resources :favourite_foods
  resources :favourite_drinks
  resources :ailments
  resources :star_signs
  resources :lastnames
  resources :firstnames
  resources :characters
  root 'characters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/age.rb
class Age < ApplicationRecord
end

app/models/ailment.rb
class Ailment < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
end

app/models/eye_colour.rb
class EyeColour < ApplicationRecord
end

app/models/favourite_drink.rb
class FavouriteDrink < ApplicationRecord
end

app/models/favourite_food.rb
class FavouriteFood < ApplicationRecord
end

app/models/firstname.rb
class Firstname < ApplicationRecord
end

app/models/gender.rb
class Gender < ApplicationRecord
end

app/models/lastname.rb
class Lastname < ApplicationRecord
end

app/models/moral_alignment.rb
class MoralAlignment < ApplicationRecord
end

app/models/mother_tongue.rb
class MotherTongue < ApplicationRecord
end

app/models/nationality.rb
class Nationality < ApplicationRecord
end

app/models/obsession.rb
class Obsession < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
end

app/models/order_alignment.rb
class OrderAlignment < ApplicationRecord
end

app/models/secret_language.rb
class SecretLanguage < ApplicationRecord
end

app/models/skin_base_tone.rb
class SkinBaseTone < ApplicationRecord
end

app/models/star_sign.rb
class StarSign < ApplicationRecord
end

app/controllers/skin_base_tones_controller.rb
class SkinBaseTonesController < ApplicationController
  before_action :set_skin_base_tone, only: [:show, :edit, :update, :destroy]

  # GET /skin_base_tones
  # GET /skin_base_tones.json
  def index
    @skin_base_tones = SkinBaseTone.all
  end

  # GET /skin_base_tones/1
  # GET /skin_base_tones/1.json
  def show
  end

  # GET /skin_base_tones/new
  def new
    @skin_base_tone = SkinBaseTone.new
  end

  # GET /skin_base_tones/1/edit
  def edit
  end

  # POST /skin_base_tones
  # POST /skin_base_tones.json
  def create
    @skin_base_tone = SkinBaseTone.new(skin_base_tone_params)

    respond_to do |format|
      if @skin_base_tone.save
        format.html { redirect_to @skin_base_tone, notice: 'Skin base tone was successfully created.' }
        format.json { render :show, status: :created, location: @skin_base_tone }
      else
        format.html { render :new }
        format.json { render json: @skin_base_tone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skin_base_tones/1
  # PATCH/PUT /skin_base_tones/1.json
  def update
    respond_to do |format|
      if @skin_base_tone.update(skin_base_tone_params)
        format.html { redirect_to @skin_base_tone, notice: 'Skin base tone was successfully updated.' }
        format.json { render :show, status: :ok, location: @skin_base_tone }
      else
        format.html { render :edit }
        format.json { render json: @skin_base_tone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skin_base_tones/1
  # DELETE /skin_base_tones/1.json
  def destroy
    @skin_base_tone.destroy
    respond_to do |format|
      format.html { redirect_to skin_base_tones_url, notice: 'Skin base tone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skin_base_tone
      @skin_base_tone = SkinBaseTone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skin_base_tone_params
      params.require(:skin_base_tone).permit(:content)
    end
end

app/helpers/ailments_helper.rb
module AilmentsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/skin_base_tones_helper.rb
module SkinBaseTonesHelper
end

app/views/skin_base_tones/_form.html.erb
<%= form_with(model: skin_base_tone, local: true) do |form| %>
  <% if skin_base_tone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skin_base_tone.errors.count, "error") %> prohibited this skin_base_tone from being saved:</h2>

      <ul>
      <% skin_base_tone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :skin_base_tone_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skin_base_tones/edit.html.erb
<h1>Editing Skin Base Tone</h1>

<%= render 'form', skin_base_tone: @skin_base_tone %>

<%= link_to 'Show', @skin_base_tone %> |
<%= link_to 'Back', skin_base_tones_path %>

app/views/skin_base_tones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skin Base Tones</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skin_base_tones.each do |skin_base_tone| %>
      <tr>
        <td><%= skin_base_tone.content %></td>
        <td><%= link_to 'Show', skin_base_tone %></td>
        <td><%= link_to 'Edit', edit_skin_base_tone_path(skin_base_tone) %></td>
        <td><%= link_to 'Destroy', skin_base_tone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skin Base Tone', new_skin_base_tone_path %>

app/views/skin_base_tones/new.html.erb
<h1>New Skin Base Tone</h1>

<%= render 'form', skin_base_tone: @skin_base_tone %>

<%= link_to 'Back', skin_base_tones_path %>

app/views/skin_base_tones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @skin_base_tone.content %>
</p>

<%= link_to 'Edit', edit_skin_base_tone_path(@skin_base_tone) %> |
<%= link_to 'Back', skin_base_tones_path %>